#!/usr/bin/env bash
set -euo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}/ssh-skill"
env_file="$config_home/env"
ssh_dir="$HOME/.ssh"
ssh_config="$ssh_dir/config"
ssh_config_dir="$ssh_dir/config.d"
cluster_config="$ssh_config_dir/aspuru-guzik-clusters"
control_dir="$ssh_dir/controlmasters"

mkdir -p "$config_home" "$ssh_dir" "$ssh_config_dir" "$control_dir"
chmod 700 "$ssh_dir" "$ssh_config_dir" "$control_dir"

if [ -f "$env_file" ]; then
  # shellcheck disable=SC1090
  . "$env_file"
fi

use_keychain_line=""
if [ "$(uname -s)" = "Darwin" ]; then
  use_keychain_line="    UseKeychain yes"
fi

is_valid_name() {
  case "$1" in
    ''|*[!A-Za-z0-9._-]*) return 1 ;;
    *) return 0 ;;
  esac
}

prompt_value() {
  var_name="$1"
  prompt="$2"
  default_value="${3:-}"
  current_value="${!var_name:-}"

  if [ -n "$current_value" ]; then
    printf '%s\n' "$current_value"
    return
  fi

  if [ -n "$default_value" ]; then
    printf '%s [%s]: ' "$prompt" "$default_value" >&2
  else
    printf '%s: ' "$prompt" >&2
  fi

  read -r answer
  if [ -z "$answer" ]; then
    answer="$default_value"
  fi
  printf '%s\n' "$answer"
}

quote_sh() {
  value="$1"
  value=${value//\'/\'\\\'\'}
  printf "'%s'" "$value"
}

alliance_user="$(prompt_value SSH_SKILL_ALLIANCE_USER 'Alliance/CCDB username')"
matter_user="$(prompt_value SSH_SKILL_MATTER_USER 'Matter/CSLab username for Mariana/Comte' "${USER}")"

if ! is_valid_name "$alliance_user"; then
  printf 'Invalid Alliance username: %s\n' "$alliance_user" >&2
  exit 1
fi

if ! is_valid_name "$matter_user"; then
  printf 'Invalid Matter/CSLab username: %s\n' "$matter_user" >&2
  exit 1
fi

key_path="${SSH_SKILL_KEY:-}"
if [ -z "$key_path" ]; then
  if [ -f "$ssh_dir/id_ed25519.pub" ]; then
    key_path="$ssh_dir/id_ed25519"
  elif [ -f "$ssh_dir/id_rsa.pub" ]; then
    key_path="$ssh_dir/id_rsa"
  else
    key_path="$ssh_dir/id_ed25519"
    printf 'No SSH public key found. Generating %s ...\n' "$key_path" >&2
    ssh-keygen -t ed25519 -f "$key_path" -C "${alliance_user}@$(hostname)-alliance" -N ''
  fi
fi

if [ ! -f "$key_path.pub" ]; then
  printf 'Missing public key: %s.pub\n' "$key_path" >&2
  exit 1
fi

chmod 600 "$key_path" 2>/dev/null || true
chmod 644 "$key_path.pub" 2>/dev/null || true

cat > "$env_file" <<EOF
export SSH_SKILL_ALLIANCE_USER=$(quote_sh "$alliance_user")
export SSH_SKILL_MATTER_USER=$(quote_sh "$matter_user")
export SSH_SKILL_KEY=$(quote_sh "$key_path")
EOF
chmod 600 "$env_file"

cat > "$cluster_config" <<EOF
# Generated by aspuru-guzik-group/ssh-skill.
# Re-run scripts/install_ssh_config.sh to update usernames or key paths.

Host mariana
    HostName mariana.matter.sandbox
    User ${matter_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ForwardAgent yes
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host comte
    HostName comte.matter.sandbox
    User ${matter_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host niagara
    HostName niagara.computecanada.ca
    User ${alliance_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host beluga
    HostName beluga.computecanada.ca
    User ${alliance_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host narval
    HostName narval.computecanada.ca
    User ${alliance_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host cedar
    HostName cedar.computecanada.ca
    User ${alliance_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3

Host killarney
    HostName killarney.alliancecan.ca
    User ${alliance_user}
    IdentityFile ${key_path}
    IdentitiesOnly yes
    AddKeysToAgent yes
${use_keychain_line}
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%C
    ControlPersist 10h
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF
chmod 600 "$cluster_config"

touch "$ssh_config"
chmod 600 "$ssh_config"
if ! grep -Eq '^[[:space:]]*Include[[:space:]]+.*\.ssh/config\.d/\*' "$ssh_config"; then
  cp "$ssh_config" "$ssh_config.bak.$(date +%Y%m%d%H%M%S)"
  {
    printf 'Include ~/.ssh/config.d/*\n'
    cat "$ssh_config"
  } > "$ssh_config.tmp"
  mv "$ssh_config.tmp" "$ssh_config"
  chmod 600 "$ssh_config"
fi

printf '\nSSH skill setup complete.\n'
printf 'Environment file: %s\n' "$env_file"
printf 'SSH cluster config: %s\n' "$cluster_config"
printf '\nAdd this public key to CCDB SSH keys / authorized keys:\n\n'
cat "$key_path.pub"
printf '\n\nAfter CCDB propagation, test with:\n'
printf '  ssh narval\n'
printf '  ssh killarney\n'
